name: "Cloud Run No Build / With Environment Values"
description: "Fork from https://github.com/stefda/action-cloud-run, adding env files to the actions file"
author: "Julius Biskopstø <jbiskur@gmail.com>"
branding:
  icon: "arrow-up-circle"
  color: "green"
inputs:
  image:
    description: "Name of the docker image"
    required: true
  service:
    description: "Name of the service in Cloud Run"
    required: true
  project:
    description: "GCP project"
    required: true
  region:
    description: "GCP region"
    required: true
  service key:
    description: "GCP service key with storage and run permissions"
    required: true
  env:
    description: "File path to environment configuration"
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
